# Generated by Django 2.1.3 on 2018-12-19 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_author_book'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='book',
        ),
    ]
