# Generated by Django 2.1.3 on 2018-12-20 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20181219_0331'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
